org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.caching=true
org.gradle.parallel=true
gradle.cache.push=false

mod_id=heart_crystals
mod_name=Heart Crystals
mod_version=3.0.0
mc_version=1.21.1

neoforge=21.1.196
parchment=2024.11.17
blueprint=8.0.0
jei=19.21.0.247
clayworks=4.0.0
gallery=2.0.0