modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/rosevcook/heart_crystals/issues"
license = "All Rights Reserved"

[[mods]]
    modId = "heart_crystals"
    version = "1.0.0"
    displayName = "Heart Crystals"
    logoFile = "logo.png"
    itemIcon = "heart_crystals:heart_crystal"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/heart_crystals"
    authors = "Rose"
    description = '''bah'''

[[dependencies.heart_crystals]]
    modId = "forge"
    mandatory = true
    versionRange = "[43.2.0,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.heart_crystals]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.heart_crystals]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[6.1.2,)"
    ordering = "BEFORE"
    side = "BOTH"

